// Hand-written scripts used when no ANTHROPIC_API_KEY is configured, so the
// whole pipeline can be demoed offline. Factual niches are kept accurate.
const s = (narration, visual) => ({ narration, visual });

export const LIBRARY = {
  scary: [{
    title: 'Room 313 Called the Front Desk',
    description: 'The phone rang at 3 a.m. The room has been sealed since 1987.',
    hashtags: ['scarystories', 'horrortok', 'creepy', 'storytime', 'haunted'],
    scenes: [
      s('I work the night desk at an old hotel. At 3 a.m., the phone rang. It was room 313.', 'a dim hotel front desk at night, an old telephone glowing under a single brass lamp'),
      s("Room 313 has been sealed since the fire in 1987. There's no phone in there. There's nothing in there.", 'a dark hotel corridor, a boarded-up door numbered 313 with scorch marks around the frame'),
      s("I picked up anyway. A little girl whispered, 'Can you bring more towels? The water's getting hot.'", 'close-up of a vintage telephone receiver in a trembling hand, deep shadows'),
      s('I told myself it was a prank. Kids from town, daring each other to call the haunted hotel.', 'an old hotel exterior on a foggy night, one window faintly lit'),
      s("But the caller ID didn't show a number. It just said: three, one, three.", 'a small glowing display on a desk phone showing the number 313 in the dark'),
      s('At 3:13, the elevator opened on my floor. Empty. The button for the third floor was glowing.', 'open elevator doors revealing an empty elevator, one button glowing red'),
      s("I didn't go up. I locked myself in the back office and waited for sunrise.", 'a locked office door seen from inside, a sliver of light under the door'),
      s('In the morning, the day manager found a stack of towels outside room 313. Neatly folded. Still warm.', 'a neat stack of white towels on the floor outside a sealed hotel door, morning light'),
      s("And a note, in crayon: 'Thank you for not coming. It isn't safe up here.'", "a child's crayon note on old paper resting on folded towels"),
      s('I quit that day. Last week, the new night clerk called me. The phone had rung. Room 313.', 'a lonely hotel lobby at night seen through rain-streaked glass'),
    ],
  }],
  history: [{
    title: 'The War Australia Lost… to Birds',
    description: 'In 1932 Australia sent machine guns against 20,000 emus. It did not go well.',
    hashtags: ['history', 'historytok', 'emuwar', 'australia', 'didyouknow'],
    scenes: [
      s('In 1932, Australia went to war. The enemy? Around twenty thousand emus.', 'vast Western Australian wheat field at golden hour with a huge flock of emus'),
      s('After breeding season, the giant birds swarmed farms in Western Australia, trampling wheat and smashing fences.', 'emus running through broken wooden fences in a wheat farm, dust in the air'),
      s('Many of the farmers were First World War veterans. So they asked the government for machine guns.', '1930s Australian farmers in hats gathered around a wooden table, sepia tones'),
      s('The Minister of Defence agreed. Major Meredith arrived with two soldiers, two Lewis guns, and ten thousand rounds.', '1930s soldiers with a mounted Lewis gun on a truck in the outback'),
      s('It did not go to plan. Every time the soldiers got close, the emus split into small groups and scattered.', 'emus scattering in every direction across red outback dirt'),
      s('In one ambush they waited for a flock of about a thousand birds. The gun jammed after hitting only a dozen.', 'a frustrated soldier behind a jammed machine gun, emus running in the distance'),
      s('After about a week, the army withdrew. Meredith said the emus could face machine guns with the invulnerability of tanks.', 'a lone emu standing proudly on a hill at sunset'),
      s('A second attempt followed. Meredith claimed 986 kills using nearly ten thousand rounds. About ten bullets per bird.', 'empty brass shell casings scattered on dry outback ground'),
      s('The emus kept coming. Farmers asked for the army again in later years, and were refused.', 'emus grazing peacefully in a wheat field under a wide blue sky'),
      s('Nearly a century later, it is remembered as the Great Emu War. The war the birds won.', 'a victorious flock of emus silhouetted against a dramatic sunset'),
    ],
  }],
  mythology: [{
    title: 'Pandora Never Had a Box',
    description: 'The real myth of Pandora — and the one thing left inside.',
    hashtags: ['mythology', 'greekmythology', 'pandora', 'myths', 'legends'],
    scenes: [
      s('Prometheus stole fire from the gods and gave it to humanity. Zeus wanted revenge.', 'a titan holding a blazing torch on a mountaintop under a stormy sky'),
      s("So he ordered Hephaestus, the smith god, to shape the first woman from clay. Her name was Pandora: 'all-gifted.'", 'a god at a glowing forge sculpting a woman from clay, sparks flying'),
      s('Every god gave her a gift. Beauty. Grace. Clever words. And from Hermes, a cunning, restless mind.', 'ancient Greek gods on Mount Olympus bestowing glowing gifts on a woman'),
      s('Zeus sent her to Epimetheus, who had been warned never to accept a gift from Zeus. He accepted anyway.', 'a man in a Greek courtyard greeting a radiant woman at the gate'),
      s('Pandora carried a great sealed jar. Not a box. The box came from a mistranslation, centuries later.', 'a large ornate ancient Greek clay jar with a heavy lid, lit by candlelight'),
      s('One day, she lifted the lid.', 'close-up of hands slowly lifting the lid of an ancient jar, light spilling out'),
      s('Out poured everything that torments us. Sickness. Toil. Grief. Every evil the world had never known.', 'dark smoky shapes and shadows swirling out of an ancient jar into the sky'),
      s('Pandora slammed the lid shut. But it was too late. Only one thing remained inside.', 'a woman pressing down the lid of a jar, face full of dread'),
      s('Hope.', 'a single small warm light glowing inside a dark jar'),
      s('The Greeks still argue what that means. Was hope kept safe for us, or kept away from us?', 'ancient Greek philosophers debating among marble columns at dusk'),
    ],
  }],
  'fun-facts': [{
    title: 'Facts Your Brain Will Refuse to Believe',
    description: 'Eight true facts that sound completely made up.',
    hashtags: ['facts', 'funfacts', 'didyouknow', 'mindblown', 'learnontiktok'],
    scenes: [
      s('Oxford University is older than the Aztec Empire. Teaching there began by 1096. Tenochtitlan was founded in 1325.', 'gothic stone university spires at dawn with mist'),
      s('Octopuses have three hearts and blue blood.', 'a vivid octopus on a coral reef, glowing blue water'),
      s('Honey found in ancient Egyptian tombs, thousands of years old, had not spoiled.', 'an ancient Egyptian tomb chamber with clay pots lit by torchlight'),
      s("Botanically, bananas are berries. Strawberries aren't.", 'a bunch of bananas beside a bowl of strawberries on a bright table'),
      s('A day on Venus is longer than its year. It takes 243 Earth days to spin once, but only 225 to orbit the Sun.', 'the planet Venus glowing yellow against a starry sky'),
      s('Wombats produce cube-shaped poop.', 'a cute wombat in the Australian bush'),
      s('Sharks are older than trees. They appeared around 450 million years ago. Trees, about 385 million.', 'an ancient shark swimming through a prehistoric ocean'),
      s('And the Eiffel Tower can grow about 15 centimetres taller in summer, as its iron expands in the heat.', 'the Eiffel Tower on a hot summer day with shimmering heat haze'),
      s("Follow for more facts your brain won't believe.", 'a glowing human brain made of stars and light'),
    ],
  }],
  motivation: [{
    title: 'The Warning an Emperor Wrote Every Morning',
    description: 'Marcus Aurelius ruled Rome. This is how he prepared for every day.',
    hashtags: ['stoicism', 'motivation', 'marcusaurelius', 'mindset', 'discipline'],
    scenes: [
      s('Marcus Aurelius was the most powerful man on Earth. Emperor of Rome.', 'a marble statue of a Roman emperor in dramatic side light'),
      s('And every morning, he reminded himself of the same thing.', 'an emperor writing by candlelight in a stone room before dawn'),
      s("Today I'll meet people who are rude, ungrateful, arrogant and dishonest.", 'a crowded ancient Roman forum with stern faces'),
      s("Not to complain. To prepare. Because nothing they do can harm your character unless you let it.", 'a lone figure standing calm in a storm on a cliff'),
      s("He didn't wish for an easy day. He trained for a hard one.", 'a man running up stone steps at sunrise'),
      s('Seneca put it simply: we suffer more often in imagination than in reality.', 'a thinker gazing at the sea from a rocky shore'),
      s('Epictetus was born a slave. He taught that some things are within your control, and some are not.', 'broken chains lying on ancient stone steps in sunlight'),
      s("Your judgments. Your effort. Your response. That's your territory. Everything else is weather.", 'a lone tree standing firm on a hill as storm clouds pass'),
      s('Marcus wrote that what stands in the way becomes the way.', 'a mountain path carved through a massive boulder'),
      s("So tomorrow, before your phone, before the noise, decide who you'll be when the day pushes back.", 'a sunrise over a quiet city seen from a window'),
    ],
  }],
  heists: [{
    title: 'The $100M Heist Undone by a Sandwich',
    description: 'They beat ten layers of vault security. Then they littered.',
    hashtags: ['heist', 'truecrime', 'antwerp', 'diamonds', 'storytime'],
    scenes: [
      s('February 2003. Antwerp, Belgium. The diamond capital of the world.', 'the Antwerp diamond district at night, wet streets reflecting neon'),
      s('Two floors underground sat a vault guarded by ten layers of security. Heat sensors. Radar. A magnetic field. A lock with a hundred million combinations.', 'a massive steel vault door deep underground, lit by cold light'),
      s('Leonardo Notarbartolo had spent over two years renting an office in the building, posing as a diamond merchant.', 'a man in a suit examining diamonds through a loupe in a small office'),
      s("Over one weekend, his crew slipped past every layer and opened 123 of the vault's 160 safe-deposit boxes.", 'rows of open safe-deposit boxes inside a vault, scattered papers'),
      s('Diamonds, gold, jewellery. Loot estimated at over 100 million dollars. Most of it has never been found.', 'a pile of sparkling diamonds and gold on black velvet'),
      s('It was the perfect crime. Until they had to get rid of the evidence.', 'shadowy figures loading bags into a car at night'),
      s('In a forest off the motorway to Brussels, the crew dumped bags of rubbish.', 'garbage bags dumped among trees in a dark Belgian forest'),
      s('The landowner found them and called the police. Inside: vault documents, a video tape, and a half-eaten salami sandwich.', 'a half-eaten sandwich next to documents on a forest floor, police flashlight'),
      s('Evidence from the bags led police to the crew. Notarbartolo was convicted and sentenced to ten years.', 'a courtroom with a judge and a defendant in a suit'),
      s("Ten layers of security couldn't stop them. A sandwich did.", 'a dramatic close-up of a sandwich on a table under a spotlight'),
    ],
  }],
  space: [{
    title: 'A Teaspoon of This Weighs a Billion Tons',
    description: 'Neutron stars are the strangest objects in the universe.',
    hashtags: ['space', 'astronomy', 'neutronstar', 'universe', 'science'],
    scenes: [
      s('When a giant star dies, it explodes in a supernova. But sometimes its core survives.', 'a massive supernova explosion in deep space, glowing shockwaves'),
      s('Gravity crushes that core until protons and electrons merge into neutrons. The result is a neutron star.', 'a tiny intensely bright star surrounded by swirling gas'),
      s('It packs more mass than our Sun into a ball about twenty kilometres wide. Roughly the size of a city.', 'a glowing neutron star hovering over a city skyline for scale'),
      s('A single teaspoon of it would weigh around a billion tons on Earth.', 'a silver teaspoon holding a glowing speck of starlight'),
      s('Some spin hundreds of times per second, sweeping beams of radiation across space like a lighthouse. We call them pulsars.', 'a pulsar emitting two bright beams of light into space'),
      s("Their gravity is so strong that light bends around them. You could see part of the star's far side.", 'light bending around a dense glowing sphere in space'),
      s("Their magnetic fields can be trillions of times stronger than Earth's.", 'glowing magnetic field lines arcing around a star'),
      s('When two neutron stars collide, they forge heavy elements like gold and platinum.', 'two bright stars spiralling into each other with a golden explosion'),
      s('Which means the gold in your jewellery may have been made when dead stars collided.', 'a gold ring glowing with cosmic light and stardust'),
      s("Follow for more of the universe's strangest objects.", 'a breathtaking view of the Milky Way over a mountain'),
    ],
  }],
  bible: [{
    title: 'Five Smooth Stones',
    description: 'David and Goliath — 1 Samuel 17.',
    hashtags: ['bible', 'biblestories', 'faith', 'davidandgoliath', 'christian'],
    scenes: [
      s('For forty days, a giant stood in the Valley of Elah and mocked the armies of Israel.', 'two ancient armies facing each other across a valley at dawn'),
      s('His name was Goliath of Gath. The Hebrew text says he stood over nine feet tall, clad in bronze.', 'a towering warrior in bronze armour holding a spear'),
      s('No soldier dared to face him. Not even King Saul.', 'a worried king in his tent with frightened soldiers'),
      s('Then a shepherd boy arrived, bringing food to his older brothers. His name was David.', 'a young shepherd walking into an army camp carrying bread'),
      s("He heard the giant's challenge and said he would fight him.", 'a determined young shepherd looking toward a distant giant'),
      s('Saul offered David his own armour. David took it off. He was not used to it.', 'a boy removing heavy oversized armour inside a tent'),
      s('Instead he chose five smooth stones from a stream, and took his sling.', 'a hand picking smooth stones from a clear stream'),
      s('Goliath scorned him. David answered: I come to thee in the name of the Lord of hosts.', 'a small shepherd facing a giant warrior in an open valley'),
      s('One stone struck Goliath in the forehead, and the giant fell on his face to the earth.', 'a sling stone flying through the air toward a giant'),
      s('First Samuel, chapter seventeen. The battle is not won by size, but by faith.', 'golden light breaking through clouds over a quiet valley'),
    ],
  }],
  kindness: [{
    title: "Walter's Second Coffee",
    description: 'He bought a coffee for a stranger every morning for three years.',
    hashtags: ['wholesome', 'kindness', 'storytime', 'faithinhumanity', 'feelgood'],
    scenes: [
      s('Every morning at 7:15, an old man named Walter bought two coffees at the café where I work.', 'a cosy café at morning with an elderly man at the counter'),
      s("One for himself. And one 'for whoever needs it next.'", 'two coffee cups on a wooden counter, steam rising in sunlight'),
      s('For three years, that second coffee went to strangers. Students. Nurses. A man who had just lost his job.', 'a tired nurse smiling while receiving a coffee cup'),
      s("Then one Monday, Walter didn't come in. Or Tuesday. Or all week.", "an empty café stool by the window on a rainy morning"),
      s('On Friday, a young woman walked in holding an envelope. She was his granddaughter.', 'a young woman holding an envelope in a café doorway'),
      s('Walter had passed away peacefully that weekend. The envelope was addressed to the café.', 'an envelope on a café counter beside a vase of flowers'),
      s("Inside was a cheque, and a note in shaky handwriting: 'Keep the second coffee going.'", 'a handwritten note in shaky handwriting, warm light'),
      s("So we did. A little chalkboard by the till says: Walter's Coffee. Take one if you need one. Leave one if you can.", 'a chalkboard sign in a café with a hand-drawn coffee cup'),
      s("Two years later, it has never been empty. Not once.", 'a line of smiling people at a café counter'),
      s("Kindness doesn't end. It just changes hands.", 'two hands passing a warm cup of coffee'),
    ],
  }],
  anime: [{
    title: 'They Called Me the Blank',
    description: 'Everyone at the academy had a power. Except me. Or so they thought.',
    hashtags: ['anime', 'animestory', 'animeedit', 'story', 'otaku'],
    scenes: [
      s('At Seiran Academy, every student awakens a power by fifteen. I was sixteen. Nothing.', 'an anime academy courtyard with cherry blossoms, a lonely student'),
      s('They called me the Blank. Even the teachers stopped calling on me.', 'anime classmates laughing at a quiet student in a classroom'),
      s("My rival, Kaito, could summon lightning. He never let me forget what I wasn't.", 'an anime rival crackling with blue lightning, smirking'),
      s('Then came the entrance trial. A sealed arena. One exit. And a creature no one had ever beaten.', 'a massive shadowy anime monster in a stone arena'),
      s('The monster absorbed every power thrown at it. Lightning. Fire. Ice. It only grew stronger.', 'an anime monster absorbing streams of fire and lightning'),
      s('Kaito went down. Then the others. I was the only one left standing. Because I had nothing it could take.', 'defeated students on the arena floor, one student standing alone'),
      s('I walked straight up to it. And for the first time, it hesitated.', 'anime hero walking calmly toward a towering monster'),
      s('My hand touched its armour, and every stolen power simply vanished.', 'a glowing hand touching dark armour, energy dissolving into light'),
      s('My power was never missing. It was nullification. And it had been waiting for something worth erasing.', 'anime hero with glowing white eyes, wind blowing through hair'),
      s("Kaito looked up at me from the floor. 'Who are you?' I smiled. 'Just the Blank.'", 'anime hero offering a hand to a fallen rival, sunset behind'),
    ],
  }],
  drama: [{
    title: 'She Stole My Project. I Kept Receipts.',
    description: 'My best friend took credit for our science fair project. Big mistake.',
    hashtags: ['storytime', 'drama', 'schooldrama', 'karma', 'revenge'],
    scenes: [
      s('My best friend Jess and I spent six weeks on our science fair project. A solar-powered water filter.', 'two students building a science project in a garage'),
      s("The night before the fair, she texted: 'I'm sick, can you bring everything?' So I did.", 'a phone screen glowing in a dark bedroom at night'),
      s("When I got there, her name was the only one on the board. She'd registered it solo.", 'a science fair display board with one name, a shocked student'),
      s("She told the judges I 'helped with the poster.' Everyone believed her. She's the popular one.", 'a confident popular girl talking to judges at a science fair'),
      s("What Jess forgot is that I'm a nerd. And nerds document everything.", 'a student with glasses smiling knowingly, holding a laptop'),
      s("When the judges asked how the filter's membrane worked, she froze.", 'a nervous student freezing in front of judges with clipboards'),
      s('So I raised my hand and asked if I could show them something. Our shared folder.', 'a laptop screen showing folders full of files'),
      s('Six weeks of timestamped notes, test results and videos. Every entry: mine.', 'judges leaning in to look at a laptop screen'),
      s('The judges moved my name to the top. Jess was disqualified. Then she had to watch me win.', 'a student holding a first-place ribbon on a stage'),
      s("Moral of the story: if you steal from a nerd, delete the version history first.", 'a smug student walking down a school hallway'),
    ],
  }],
};

// Pick a script the series hasn't used yet (or the least recent one).
export function libraryScript(nicheId, usedTitles = []) {
  const pool = LIBRARY[nicheId] || Object.values(LIBRARY).flat();
  const unused = pool.filter((sc) => !usedTitles.includes(sc.title));
  const pick = (unused.length ? unused : pool)[Math.floor(Math.random() * (unused.length || pool.length))];
  return structuredClone(pick);
}
